id: jms_trigger_sonicmq
namespace: at.conapi

triggers:
  - id: jms-trigger
    type: io.kestra.plugin.jms.RealtimeTrigger
    connectionFactoryConfig:
      type: DIRECT
      # Enable FilteredClassLoader for SonicMQ which bundles javax.jms classes in its JAR
      useFilteredClassLoader: true
      connectionFactoryClass: progress.message.jclient.ConnectionFactory
      username: Administrator
      password: Administrator
      connectionProperties:
        connectionURLs: tcp://host.docker.internal:2506
    destination:
      destinationName: SampleQ2
      destinationType: QUEUE

tasks:
  - id: logoutputs
    type: io.kestra.plugin.core.log.Log
    message: '{{ trigger.data }}'