id: jms_trigger_rabbitmq
namespace: io.kestra.examples

description: |
  Trigger a flow when a message arrives on a RabbitMQ queue.

  Prerequisites:
  - Build: ./gradlew build -x test
  - Start: docker-compose -f src/examples/docker/docker-compose-rabbitmq.yml up
  - Send messages using jms_produce_rabbitmq.yaml to trigger this flow

tasks:
  - id: process_message
    type: io.kestra.plugin.core.log.Log
    message: "Received message: {{ trigger.data }}"

  - id: log_metadata
    type: io.kestra.plugin.core.log.Log
    message: |
      Message ID: {{ trigger.messageId }}
      Timestamp: {{ trigger.timestamp }}

triggers:
  - id: watch_queue
    type: io.kestra.plugin.jms.RealtimeTrigger
    connectionFactoryConfig:
      type: DIRECT
      connectionFactoryClass: com.rabbitmq.jms.admin.RMQConnectionFactory
      connectionProperties:
        host: rabbitmq
        port: "5672"
        username: guest
        password: guest
        virtualHost: /
    destination:
      destinationName: kestra.example.queue
      destinationType: QUEUE
    serdeType: STRING
